# Generated by Django 3.2.9 on 2022-03-14 04:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('QC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='voice',
            field=models.OneToOneField(limit_choices_to={'created_date__gte': datetime.datetime(2022, 3, 14, 7, 59, 41, 584784)}, on_delete=django.db.models.deletion.CASCADE, related_name='voice', to='QC.voice'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='voice_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2022, 3, 14)),
        ),
    ]
