# Generated by Django 3.2.9 on 2022-03-14 05:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QC', '0002_auto_20220314_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voice',
            name='comment',
        ),
        migrations.AddField(
            model_name='indicators',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='voice',
            field=models.OneToOneField(limit_choices_to={'created_date__gte': datetime.datetime(2022, 3, 14, 8, 40, 47, 317359)}, on_delete=django.db.models.deletion.CASCADE, related_name='voice', to='QC.voice'),
        ),
    ]
