# Generated by Django 3.2.9 on 2022-04-30 05:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('QC', '0005_auto_20220430_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicators',
            name='voice',
            field=models.OneToOneField(limit_choices_to={'created_date__gte': datetime.datetime(2022, 4, 30, 10, 0, 9, 887444)}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice', to='QC.voice'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='voice_call',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 30, 10, 1, 9, 887444)),
        ),
        migrations.AlterField(
            model_name='voice',
            name='voice_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2022, 4, 30)),
        ),
    ]
