# Generated by Django 3.2.9 on 2022-04-30 05:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QC', '0006_auto_20220430_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicators',
            name='voice',
            field=models.OneToOneField(limit_choices_to={'created_date__gte': datetime.datetime(2022, 4, 30, 10, 5, 36, 134979)}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice', to='QC.voice'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='voice_call',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 30, 10, 6, 36, 134979)),
        ),
        migrations.AlterField(
            model_name='voice',
            name='voice_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 30, 10, 6, 36, 134979)),
        ),
    ]
