service:
  type: NodePort
  ports:
   - port: 80
     targetPort: 80
     name: http
     protocol: TCP
     nodePort: 31096
probeEnable: false
env:
  name: deployment
  profile: Development

resources: 
   limits:
     cpu: 2000m
     memory: 2048Mi
   requests:
     cpu: 1000m
     memory: 1024Mi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3

