# Generated by Django 3.2.9 on 2022-04-09 11:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields.related
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('result', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='result.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='QcOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('qc_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_agent', to='result.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='SetPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_score', models.IntegerField(default=10)),
                ('allowed_remark', models.IntegerField(default=3)),
                ('allowed_warning', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_leader', to='result.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_name', models.CharField(max_length=30)),
                ('voice_date', django_jalali.db.models.jDateField(default=datetime.date(2022, 4, 9))),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('agent_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='result.customuser')),
                ('leader', models.ForeignKey(on_delete=django.db.models.fields.related.ForeignKey, related_name='teamlead', to='QC.leader')),
                ('qc_operator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='qc', to='QC.qcoperator')),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sarteam', to='QC.teamleader')),
            ],
        ),
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_sentences', models.BooleanField(default=False)),
                ('say_customer_name', models.BooleanField(default=False)),
                ('speaking_tone', models.BooleanField(default=False)),
                ('respect_to_customer', models.BooleanField(default=False)),
                ('anger_management', models.BooleanField(default=False)),
                ('proper_interaction', models.BooleanField(default=False)),
                ('do_not_use_negative_verbs', models.BooleanField(default=False)),
                ('effective_listening', models.BooleanField(default=False)),
                ('interrupt_customer_talk', models.BooleanField(default=False)),
                ('correct_customer_guidance', models.BooleanField(default=False)),
                ('proper_registration_complaint', models.BooleanField(default=False)),
                ('familiarity_with_application_site', models.BooleanField(default=False)),
                ('familiarity_with_okala_panel', models.BooleanField(default=False)),
                ('proper_hold', models.BooleanField(default=False)),
                ('observe_hold_law', models.BooleanField(default=False)),
                ('unnecessary_referral_to_another_unit', models.BooleanField(default=False)),
                ('express_unnecessary_issues', models.BooleanField(default=False)),
                ('call_duration_management', models.BooleanField(default=False)),
                ('negotiation', models.BooleanField(default=False)),
                ('final_sentences', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('score_from_hundred', models.PositiveIntegerField(blank=True, null=True)),
                ('voice', models.OneToOneField(limit_choices_to={'created_date__gte': datetime.datetime(2022, 4, 9, 15, 56, 30, 901760)}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice', to='QC.voice')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_remark', models.IntegerField(default=0)),
                ('number_of_warning', models.IntegerField(default=0)),
                ('number_of_retraining', models.IntegerField(default=0)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_warning', to='result.customuser')),
            ],
        ),
    ]
