# Generated by Django 3.2.9 on 2022-02-26 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('result', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_name', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('agent_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='result.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Sleepy_voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_indicator', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('voice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice', to='QC.voice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
