# Generated by Django 3.2.9 on 2022-04-09 12:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicators',
            name='voice',
            field=models.OneToOneField(limit_choices_to={'created_date__gte': datetime.datetime(2022, 4, 9, 16, 31, 46, 270157)}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice', to='QC.voice'),
        ),
    ]
