# Generated by Django 3.2.9 on 2022-02-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QC', '0002_rename_sleepy_voice_sleepyvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleepyvoice',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleepyvoice',
            name='voice_date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
