# Generated by Django 3.2.9 on 2022-04-27 16:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('QC', '0003_auto_20220425_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='voice_call',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 20, 42, 26, 757151)),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='voice',
            field=models.OneToOneField(limit_choices_to={'created_date__gte': datetime.datetime(2022, 4, 27, 20, 41, 26, 757151)}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice', to='QC.voice'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='voice_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2022, 4, 27)),
        ),
    ]
