# Generated by Django 3.2.9 on 2022-02-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(default='aljlsdf', max_length=500),
            preserve_default=False,
        ),
    ]
