# Generated by Django 3.2.9 on 2022-02-02 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0002_message_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
