# Generated by Django 3.2.9 on 2022-02-02 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('result', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('TR', 'training'), ('NE', 'news')], max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_size', models.PositiveIntegerField(default=20)),
                ('color', models.CharField(default='black', max_length=10)),
                ('text_align', models.CharField(default='justify', max_length=10)),
                ('background_color', models.CharField(default='white', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(choices=[('IN', 'inbound'), ('OUT', 'outbound'), ('CRM', 'crm'), ('MJ', 'marjouee'), ('ALL', 'all')], max_length=3)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='billboard.category')),
                ('configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='billboard.configuration')),
                ('group_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='billboard.groupmessage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='result.customuser')),
            ],
        ),
    ]
