# Generated by Django 3.2.9 on 2022-02-05 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0003_remove_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billboard.category'),
        ),
        migrations.AlterField(
            model_name='message',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billboard.configuration'),
        ),
        migrations.AlterField(
            model_name='message',
            name='group_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billboard.groupmessage'),
        ),
    ]
