services:
    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
        - pgdata:/var/lib/postgresql/data
    sticker:
        build:
            context: .
        ports:
        - "8000:80"
        volumes:
            - .:/app
        depends_on:
            - db
volumes:
    pgdata:
